import { AuthProvider } from "@/contexts/auth";
import "@/styles/globals.css";

export const metadata = {
  title: "Bingo Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
